/*this program reads a string and prints it in alphabetical order.*/
#include<stdio.h>
#include<conio.h>
#include<string.h>
void main()
{
    int i,j,k,l,length,length1,length2,temp1,temp2,temp3,temp;
    char str1[100],str2[100],str3[100],tempstr[100];
    temp1=0;
    temp2=0;
    temp3=0;
    char str[100];
    printf("this program reads a string and prints it in alphabetical order.\n");
    printf("\n-----------------------------------------------------------------------------------------------------------------------\n");
    printf("enter a string having maximum 100 characters:\n");
    gets(str);
    length=strlen(str);
    for(i=0;i<length;i++)
    {
        if(str[i]>=65 && str[i]<=90)
        {
            for(j=temp1;j<length;j++)
            {
                str1[j]=str[i];
                break;
            }
            temp1++;
        }
        else if(str[i]>=97 && str[i]<=122)
        {
            for(k=temp2;k<length;k++)
            {
                str2[k]=str[i];
                break;
            }
            temp2++;
        }
        else
        {
            for(l=temp3;l<length;l++)
            {
                str3[l]=str[i];
                break;
            }
            temp3++;
        }
    }
    /*length1=strlen(str1);
    length2=strlen(str2);
    for(i=0;i<length1;i++)
    {
        for(j=i+1;j<length1;j++)
        {
            if(str1[i]>str1[j])
            {
                temp=str1[i];
                str1[i]=str1[j];
                str1[j]=temp;
            }
        }
    }
    for(i=0;i<length2;i++)
    {
        for(j=i+1;j<length2;j++)
        {
            if(str2[i]>str2[j])
            {
                temp=str2[i];
                str2[i]=str2[j];
                str2[j]=temp;
            }
        }
    }*/
    /*strcpy(tempstr,str1);
    strlwr(tempstr);
    temp=0;
    temp1=0;
    temp2=0;
    for(i=temp1;i<length1;i++)
    {
        for(j=temp2;j<length2;j++)
        {
            if(tempstr[i]<str2[j])
            {
                for(k=temp;k<length;k++)
                {
                    str[k]=str1[i];
                    temp++;
                    temp1++;
                    break;
                }
            }
            else
            {
                for(k=temp;k<length;k++)
                {
                    str[k]=str2[j];
                    temp++;
                    temp2++;
                    break;
                }
            }
            break;
        }
    }*/
    //strcat(str,str3);
    puts(str2);
    getch();
}
